export const eventos = [
  {
    id: 'cc566d00-a09e-42b4-9b73-8371f61cb29f',
    title: 'Festival Sunset Beats',
    date: '25',
    month: 'ABR',
    time: '19:00',
    venue: 'Teatro Municipal',
    city: 'São Paulo',
    price: 'R$ 120',
    description: 'Música eletrônica com DJs nacionais.',
    organizer: 'Sunset Events',
    image: require('../images/Festival-Kyan.png'),
  },
  {
    id: 'cb93e45f-52da-421b-af6e-2f7401288f6f',
    title: 'Show Acústico Open Air',
    date: '02',
    month: 'MAI',
    time: '18:30',
    venue: 'Praça Central',
    city: 'São Paulo',
    price: 'R$ 80',
    description: 'Apresentações acústicas com talentos locais.',
    organizer: 'Open Air Eventos',
    image: require('../images/Festival-Recaydjpg.jpg'),
  },
  {
    id: '4ba8c608-3880-49ff-91a3-fb1d5627f548',
    title: 'Noite de Jazz & Vinil',
    date: '09',
    month: 'MAI',
    time: '20:00',
    venue: 'Bar do Jazz',
    city: 'São Paulo',
    price: 'R$ 110',
    description: 'Sessão íntima com bandas de jazz.',
    organizer: 'Jazz Club',
    image: require('../images/Festival-RyuTheRunner.jpg'),
  },
  {
    id: '4287e048-52e5-4101-8c36-a4d1bc90098f',
    title: 'Stand-up Comedy Prime',
    date: '15',
    month: 'MAI',
    time: '21:00',
    venue: 'Teatro Rio',
    city: 'São Paulo',
    price: 'R$ 90',
    description: 'Os melhores comediantes em espetáculo.',
    organizer: 'Comedy Brasil',
    image: require('../images/Festival-Travis.png'),
  },
  {
    id: '0cdbbe60-5291-41ad-ac31-8694cf1f032a',
    title: 'Noite Indie Rock',
    date: '22',
    month: 'MAI',
    time: '20:30',
    venue: 'Clube 79',
    city: 'São Paulo',
    price: 'R$ 100',
    description: 'Bandas independentes em ambiente underground.',
    organizer: 'Rock Club',
    image: require('../images/Festival-Veigh.jpeg'),
  },
  {
    id: '8eca6294-3e1b-4290-b3bd-3a68f320d8f7',
    title: 'Festival de Música Latina',
    date: '29',
    month: 'MAI',
    time: '19:30',
    venue: 'Arena Verde',
    city: 'São Paulo',
    price: 'R$ 130',
    description: 'Ritmos latinos, dança e show visual.',
    organizer: 'Latina Events',
    image: require('../images/Festival-Vino.png'),
  },
];

export const developers = [
  {
    id: "1",
    name: "Bruno Amaro de Souza",
    role: "Desenvolvedor Front-end",
    image: require("../images/Foto de Perfil/Tata.jpg"),
  },
  {
    id: "2",
    name: "Pedro Henrique de Oliveira",
    role: "Desenvolvedor Front-end",
    image: require("../images/Foto de Perfil/Davi-Brito.png"),
  },
  {
    id: "3",
    name: "Rayner Yago",
    role: "Desnvolvedor Mobile",
    image: require("../images/Foto de Perfil/Davy-Jones.jpg"),
  },
  {
    id: "4",
    name: "Maykon Oliveira Almeida",
    role: "Design UX/UI & Desenvolvedor Front-end",
    image: require("../images/Foto de Perfil/Faiska.jpg"),
  },
  {
    id: "5",
    name: "Gabriel ??????? ",
    role: "Desenvolvedor Front-end",
    image: require("../images/Foto de Perfil/EduKof.png"),
  },
];

export const tarefas = [
  {
    id: "2fa56699-5412-496e-af93-9dde1d109d26",
    title: "1. Planejamento do evento",
    description: "Definir local, data, orçamento, fornecedores, cronograma e necessidades do cliente para garantir que o evento aconteça conforme o planejado.",
  },
  {
    id: "06d6ebf3-e6e1-44e7-80b9-d840411b37fc",
    title: "2. Gestão de fornecedores e estrutura",
    description: "Contratar e coordenar serviços como buffet, som, iluminação, decoração, segurança e equipamentos necessários para o evento.",
  },
  {
    id: "09b51565-0ec8-42d4-b9f1-817caab6afac",
    title: "3. Coordenação no dia do evento",
    description: "Supervisionar montagem, controlar horários, orientar equipe e resolver imprevistos para que tudo ocorra de forma organizada.",
  },
];