export const produtos = [
  {
    id: '1',
    title: 'Camiseta Box Logo',
    brand: 'Supreme',
    price: 'R$199',
    quantity: 10,
    image: require('../assets/foto1.jpg'),
  },
  {
    id: '2',
    title: 'Hoodie Alcatraz',
    brand: 'Corteiz',
    price: 'R$249',
    quantity: 6,
    image: require('../assets/foto2.jpg'),
  },
  {
    id: '3',
    title: 'Calça Cargo Street',
    brand: 'Urban Wear',
    price: 'R$179',
    quantity: 12,
    image: require('../assets/foto3.jpg'),
  },
  {
    id: '4',
    title: 'Jaqueta Windbreaker',
    brand: 'Street Division',
    price: 'R$299',
    quantity: 4,
    image: require('../assets/foto4.jpg'),
  },
  {
    id: '5',
    title: 'Boné Snapback',
    brand: 'Urban Supply',
    price: 'R$120',
    quantity: 15,
    image: require('../assets/foto5.jpg'),
  },
  {
    id: '6',
    title: 'Camiseta Oversized',
    brand: 'Street Club',
    price: 'R$159',
    quantity: 8,
    image: require('../assets/foto6.jpg'),
  },
];